INSERT INTO USERS (ORGANIZATION, LOGIN, PASSWORD_HASH, TOKEN)
    VALUES ('Home', 'sidikov', '05050505adv', '3fgsdf4');

INSERT INTO USERS (ORGANIZATION, LOGIN, PASSWORD_HASH, TOKEN)
VALUES ('Space', 'alpha', '050sds05advasd', 'sdsd323');

INSERT INTO DOMAINS (DOMAIN_VALUES)
    VALUES ('animal, human');

INSERT INTO TASKS (AUTHOR_ID, DESCRIPTION, ATTRIBUTE_DOMAIN_ID, INSTRUCTIONS_FILE_URL)
    VALUES (0, 'simple_task', 0, 'file://instructions.pdf');

INSERT INTO TASKS (AUTHOR_ID, DESCRIPTION, ATTRIBUTE_DOMAIN_ID, INSTRUCTIONS_FILE_URL)
    VALUES (0, 'simple_task_2', 0, 'file://instructions_2.pdf');

INSERT INTO TASK_ASSIGNMENTS (USER_ID, TASK_ID)
    VALUES (1,1);